create extension if not exists pgcrypto;
do $$begin create type public.app_role as enum('CEO','SUPER_ADMIN','MANAGER','ADMIN','HOST','AGENT','USER'); exception when duplicate_object then null; end$;

do $begin alter type public.app_role add value if not exists 'BD'; exception when duplicate_object then null; end$;

create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 username text unique,display_name text not null default '',avatar_url text,
 role public.app_role not null default 'USER',is_active boolean not null default true,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 activity_admin_badge boolean not null default false,customer_service_badge boolean not null default false,is_verified boolean not null default false);
create table if not exists public.wallets(user_id uuid primary key references public.profiles(id) on delete cascade,balance bigint not null default 0 check(balance>=0),updated_at timestamptz not null default now());
create table if not exists public.coin_transactions(id uuid primary key default gen_random_uuid(),from_user_id uuid references public.profiles(id),to_user_id uuid references public.profiles(id),amount bigint not null check(amount>0),reason text not null default 'transfer',created_at timestamptz not null default now());
create table if not exists public.agencies(id uuid primary key default gen_random_uuid(),name text not null unique,manager_id uuid references public.profiles(id),bd_id uuid references public.profiles(id),owner_id uuid references public.profiles(id),is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.rooms(id uuid primary key default gen_random_uuid(),name text not null,owner_id uuid references public.profiles(id),livekit_room_name text unique,is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.frame_items(id uuid primary key default gen_random_uuid(),name text not null unique,style_key text not null,price bigint not null default 0 check(price>=0),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.coin_packages(id uuid primary key default gen_random_uuid(),name text not null unique,coins bigint not null check(coins>0),price_usd numeric(12,2) not null check(price_usd>=0),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.vip_levels(id text primary key,animal text not null,image text not null,price_coins bigint not null default 0,duration_days integer not null default 30,perks jsonb not null default '[]',is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.gifts(id text primary key,name text not null,emoji text not null,price bigint not null check(price>0),is_active boolean not null default true,category text not null default 'normal',banner_enabled boolean not null default false,banner_min_price bigint not null default 4000,luck_min_win bigint not null default 3000);
create table if not exists public.rocket_levels(id integer primary key check(id between 1 and 5),name text not null,bg1 text not null default '',bg2 text not null default '',line text not null default '',coins bigint not null default 0,is_active boolean not null default true,updated_at timestamptz not null default now());
create table if not exists public.asmar_policy(level integer primary key,target bigint not null default 0,host_base bigint not null default 0,agent_base bigint not null default 0,host_total bigint not null default 0,agent_total bigint not null default 0);
create table if not exists public.app_promotions(id uuid primary key default gen_random_uuid(),title text not null,subtitle text,image_url text,first_place text,second_place text,third_place text,first_prize text,second_prize text,third_prize text,button_text text default 'شارك الآن',button_url text,starts_at timestamptz not null default now(),ends_at timestamptz,is_active boolean not null default true,created_at timestamptz not null default now());

alter table public.profiles enable row level security;alter table public.agencies enable row level security;alter table public.wallets enable row level security;alter table public.rooms enable row level security;alter table public.frame_items enable row level security;alter table public.coin_packages enable row level security;alter table public.vip_levels enable row level security;alter table public.gifts enable row level security;alter table public.rocket_levels enable row level security;alter table public.asmar_policy enable row level security;alter table public.app_promotions enable row level security;

create or replace function public.has_role(required_roles public.app_role[]) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and is_active and role=any(required_roles))$;

drop policy if exists profiles_self on public.profiles;create policy profiles_self on public.profiles for select to authenticated using(id=auth.uid() or public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists profiles_admin_update on public.profiles;create policy profiles_admin_update on public.profiles for update to authenticated using(public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[])) with check(public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists wallets_read on public.wallets;create policy wallets_read on public.wallets for select to authenticated using(user_id=auth.uid() or public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists rooms_read on public.rooms;create policy rooms_read on public.rooms for select to authenticated using(is_active or public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists frames_read on public.frame_items;create policy frames_read on public.frame_items for select to authenticated using(is_active or public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists frames_admin on public.frame_items;create policy frames_admin on public.frame_items for all to authenticated using(public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[])) with check(public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists packages_read on public.coin_packages;create policy packages_read on public.coin_packages for select to authenticated using(is_active or public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists packages_admin on public.coin_packages;create policy packages_admin on public.coin_packages for all to authenticated using(public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[])) with check(public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists vip_read on public.vip_levels;create policy vip_read on public.vip_levels for select to authenticated using(is_active or public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists vip_admin on public.vip_levels;create policy vip_admin on public.vip_levels for all to authenticated using(public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[])) with check(public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists gifts_read on public.gifts;create policy gifts_read on public.gifts for select to authenticated using(is_active or public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists gifts_admin on public.gifts;create policy gifts_admin on public.gifts for update to authenticated using(public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[])) with check(public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists rocket_read on public.rocket_levels;create policy rocket_read on public.rocket_levels for select to authenticated using(is_active or public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists rocket_admin on public.rocket_levels;create policy rocket_admin on public.rocket_levels for update to authenticated using(public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[])) with check(public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists policy_read on public.asmar_policy;create policy policy_read on public.asmar_policy for select to authenticated using(true);
drop policy if exists promo_read on public.app_promotions;create policy promo_read on public.app_promotions for select to authenticated using(is_active or public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));
drop policy if exists promo_admin on public.app_promotions;create policy promo_admin on public.app_promotions for all to authenticated using(public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[])) with check(public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]));

grant select on public.profiles,public.agencies,public.wallets,public.rooms,public.frame_items,public.coin_packages,public.vip_levels,public.gifts,public.rocket_levels,public.asmar_policy,public.app_promotions to authenticated;

insert into public.frame_items(name,style_key,price) values('الإطار الذهبي','gold',500),('إطار الماس','diamond',1500),('إطار النار','fire',2500),('إطار VIP','vip',5000),('إطار SVIP','svip',10000) on conflict(name) do nothing;
insert into public.coin_packages(name,coins,price_usd) values('Starter',1000,.99),('Popular',5500,4.99),('VIP',12000,9.99),('SVIP',30000,24.99) on conflict(name) do nothing;
insert into public.vip_levels(id,animal,image,price_coins) values('VIP1','الغزال','assets/vip/deer.png',10000),('VIP2','الذئب','assets/vip/wolf.png',20000),('VIP3','التمساح','assets/vip/crocodile.png',30000),('VIP4','الفيل','assets/vip/elephant.png',40000),('VIP5','النسر','assets/vip/eagle.png',50000),('VIP6','الدب','assets/vip/bear.png',60000),('VIP7','الفهد','assets/vip/leopard.png',70000),('VIP8','النمر','assets/vip/tiger.png',80000),('VIP9','التنين','assets/vip/dragon.png',90000),('VIP10','الأسد','assets/vip/lion.png',100000),('SVIP','ملكي','assets/vip/svip.png',250000) on conflict(id) do nothing;
insert into public.rocket_levels(id,name,bg1,bg2,line,coins) values(1,'LV1 عادي','#2A1E0F','#1A1109','#FFD700',1000),(2,'LV2 زمرد','#0F2A1E','#05140A','#00FF88',3000),(3,'LV3 ياقوت ازرق','#0F1E4A','#050A2A','#3A7BFF',5000),(4,'LV4 روبي احمر','#4A0F0F','#2A0505','#FF2A2A',7000),(5,'LV5 ملكي بنفسجي','#3A0F4A','#1A052A','#AA2AFF',10000) on conflict(id) do nothing;
insert into public.gifts(id,name,emoji,price,category,banner_enabled) values('rose','وردة','🌹',100,'normal',false),('heart','قلب','❤️',500,'love',false),('diamond','ماسة','💎',2500,'luxury',false),('crown','تاج ملكي','👑',10000,'luxury',true),('royal_car','سيارة ملكية','🚘',50000,'luxury',true),('gold_dragon','تنين ذهبي','🐉',250000,'luxury',true),('asmar_kingdom','مملكة Asmar','🏯',1000000,'luxury',true) on conflict(id) do nothing;
insert into public.app_promotions(title,subtitle,starts_at) select 'ASMAR CHAT — حدث الشحن','نافس على المراكز واربح جوائز الحدث',now() where not exists(select 1 from public.app_promotions);
insert into public.wallets(user_id,balance) select id,10000000000 from public.profiles where role='CEO' and not exists(select 1 from public.wallets w where w.user_id=profiles.id);
update public.wallets w set balance=10000000000,updated_at=now() from public.profiles p where p.id=w.user_id and p.role='CEO' and w.balance<10000000000;

create or replace function public.admin_set_user_active(p_user_id uuid,p_active boolean) returns boolean language plpgsql security definer set search_path=public as $$begin if not public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]) then raise exception 'not authorized';end if;update public.profiles set is_active=p_active,updated_at=now() where id=p_user_id;return p_active;end$$;
create or replace function public.admin_set_room_active(p_room_id uuid,p_active boolean) returns boolean language plpgsql security definer set search_path=public as $$begin if not public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]) then raise exception 'not authorized';end if;update public.rooms set is_active=p_active where id=p_room_id;return p_active;end$$;
create or replace function public.admin_adjust_wallet(p_user_id uuid,p_amount bigint) returns bigint language plpgsql security definer set search_path=public as $$declare b bigint;begin if not public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]) then raise exception 'not authorized';end if;insert into public.wallets(user_id,balance) values(p_user_id,0) on conflict do nothing;update public.wallets set balance=balance+p_amount,updated_at=now() where user_id=p_user_id and balance+p_amount>=0 returning balance into b;if b is null then raise exception 'insufficient balance';end if;return b;end$$;
create or replace function public.admin_update_gift(p_id text,p_name text,p_emoji text,p_price bigint,p_category text,p_is_active boolean,p_banner_enabled boolean,p_banner_min_price bigint,p_luck_min_win bigint) returns public.gifts language plpgsql security definer set search_path=public as $$declare g public.gifts;begin if not public.has_role(array['CEO','SUPER_ADMIN']::public.app_role[]) then raise exception 'not authorized';end if;update public.gifts set name=p_name,emoji=p_emoji,price=p_price,category=p_category,is_active=p_is_active,banner_enabled=p_banner_enabled,banner_min_price=p_banner_min_price,luck_min_win=p_luck_min_win where id=p_id returning * into g;if g.id is null then raise exception 'gift not found';end if;return g;end$$;
grant execute on function public.admin_set_user_active(uuid,boolean),public.admin_set_room_active(uuid,boolean),public.admin_adjust_wallet(uuid,bigint),public.admin_update_gift(text,text,text,bigint,text,boolean,boolean,bigint,bigint) to authenticated;
create or replace function public.admin_grant_vip(p_user_id uuid,p_vip_level text) returns text language plpgsql security definer set search_path=public as $$declare actor_role public.app_role; target_level integer; max_level integer;begin select role into actor_role from public.profiles where id=auth.uid() and is_active;if actor_role is null then raise exception 'not authorized';end if;target_level:=case when upper(p_vip_level) like 'VIP%' then regexp_replace(upper(p_vip_level),'[^0-9]','','g')::integer else 0 end;max_level:=case actor_role when 'CEO' then 10 when 'SUPER_ADMIN' then 6 else 0 end;if target_level<1 or target_level>max_level then raise exception 'VIP level not permitted for this role';end if;update public.profiles set vip_level=upper(p_vip_level),updated_at=now() where id=p_user_id;return upper(p_vip_level);end$$;
grant execute on function public.admin_grant_vip(uuid,text) to authenticated;
