workflows:
  android-workflow:
    name: Android APK
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
      - name: Get packages
        script: |
          flutter pub get
      - name: Build APK Release
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
