name: asmar_chat
description: Asmar Chat - Yalla Style Voice Rooms
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.22.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.2
  lottie: ^3.1.2
  shared_preferences: ^2.2.2
  http: ^1.2.0
  url_launcher: ^6.3.1
  image_picker: ^1.0.8
  app_links: ^6.3.3
  supabase_flutter: ^2.15.4
  livekit_client: 2.2.5
  agora_rtc_engine: ^6.6.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
