import 'package:flutter/material.dart';
import '../../../asmar/asmar_theme.dart';

class RoomGamesSheet extends StatelessWidget {
  const RoomGamesSheet({super.key});
  static const games = [('لودو', Icons.casino, '50000'), ('دومينو', Icons.grid_4x4, '50000'), ('كرة قدم', Icons.sports_soccer, '90000'), ('Ludo Pro', Icons.extension, '90000'), ('Racing', Icons.directions_car, '50000'), ('Basketball', Icons.sports_basketball, '50000'), ('Monster', Icons.pest_control, '90000'), ('Greedy', Icons.attach_money, '50000'), ('Dice', Icons.casino_outlined, '50000')];
  @override
  Widget build(BuildContext context) => Directionality(textDirection: TextDirection.rtl, child: Container(height: MediaQuery.sizeOf(context).height * .72, decoration: const BoxDecoration(color: Color(0xFF100A18), borderRadius: BorderRadius.vertical(top: Radius.circular(24))), child: SafeArea(top: false, child: Column(children: [Padding(padding: const EdgeInsets.fromLTRB(18, 16, 12, 8), child: Row(children: [const Text('لعبة شعبية', style: TextStyle(color: AsmarTheme.gold, fontSize: 20, fontWeight: FontWeight.w900)), const Spacer(), IconButton(onPressed: () => Navigator.pop(context), icon: const Icon(Icons.close, color: Colors.white54))])), Expanded(child: GridView.builder(padding: const EdgeInsets.all(14), itemCount: games.length, gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 3, crossAxisSpacing: 10, mainAxisSpacing: 12, childAspectRatio: .88), itemBuilder: (_, i) { final g=games[i]; return InkWell(onTap: () { Navigator.pop(context); ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('تم اختيار ${g.$1} - دخول ${g.$3} ذهب'))); }, child: Container(decoration: AsmarTheme.card(radius: 15), padding: const EdgeInsets.all(8), child: Column(children: [Expanded(child: Container(width: double.infinity, decoration: const BoxDecoration(gradient: LinearGradient(colors: [Color(0xFF422064), Color(0xFF1C102B)]), borderRadius: BorderRadius.all(Radius.circular(12))), child: Icon(g.$2, color: AsmarTheme.gold, size: 38))), const SizedBox(height: 6), Text(g.$1, maxLines: 1, style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 11)), Text('${g.$3} 🪙', style: const TextStyle(color: AsmarTheme.gold, fontSize: 10))]))); }))]))));
}
