import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../asmar/asmar_theme.dart';
import 'room_info_sheet.dart';
import 'room_settings_screen.dart';
import 'widgets/room_tools_sheet.dart';
import 'widgets/room_games_sheet.dart';
import 'widgets/room_gifts_sheet.dart';

class RoomScreen extends StatefulWidget {
  const RoomScreen({super.key, required this.roomName, required this.roomId});
  final String roomName;
  final String roomId;
  @override State<RoomScreen> createState() => _RoomScreenState();
}
class _RoomScreenState extends State<RoomScreen> {
  final client=Supabase.instance.client;
  late final Stream<List<Map<String,dynamic>>> _members;
  List<Map<String,dynamic>> currentMembers=[];
  bool joined=false,muted=false;
  @override void initState(){super.initState();_members=client.from('room_members').stream(primaryKey:['room_id','user_id']).eq('room_id',widget.roomId).order('seat_no');_join();}
  Future<void> _join() async {try{await client.rpc('join_room',params:{'p_room_id':widget.roomId});if(mounted)setState(()=>joined=true);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر دخول الغرفة: $e')));}}
  Future<void> _leave() async {if(!joined)return;try{await client.rpc('leave_room',params:{'p_room_id':widget.roomId});}catch(_){}}
  @override void dispose(){_leave();super.dispose();}
  void _sheet(BuildContext context,Widget child)=>showModalBottomSheet<void>(context:context,isScrollControlled:true,backgroundColor:Colors.transparent,builder:(_)=>child);
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFF1A0A3A),body:Container(decoration:const BoxDecoration(gradient:LinearGradient(colors:[Color(0xFF1A0A3A),Color(0xFF4A1A8A)],begin:Alignment.topCenter,end:Alignment.bottomCenter)),child:SafeArea(child:Column(children:[_header(context),Expanded(child:StreamBuilder<List<Map<String,dynamic>>>(stream:_members,builder:(context,s){currentMembers=s.data??const[];return _stage(currentMembers);})),_chat(),_bottomBar(context)]))));
  Widget _header(BuildContext context)=>Padding(padding:const EdgeInsets.fromLTRB(10,8,10,4),child:Row(children:[IconButton(onPressed:()async{await _leave();if(context.mounted)Navigator.pop(context);},icon:const Icon(Icons.close,color:Colors.white)),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(widget.roomName,style:const TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w900)),Text('Room: ${widget.roomId}',style:const TextStyle(color:Colors.white70,fontSize:11))])),StreamBuilder<List<Map<String,dynamic>>>(stream:_members,builder:(_,s){final online=(s.data??const[]).where((m)=>m['left_at']==null).length;return Text('🟢 $online',style:const TextStyle(color:Colors.white70,fontWeight:FontWeight.bold));}),IconButton(onPressed:()=>showModalBottomSheet(context:context,builder:(_)=>const RoomInfoSheet()),icon:const Icon(Icons.info_outline,color:Colors.white)),IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const RoomSettingsScreen())),icon:const Icon(Icons.settings_outlined,color:Colors.white)),IconButton(onPressed:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('يمكن مشاركة Room ID مع الأصدقاء'))),icon:const Icon(Icons.share_outlined,color:Colors.white))]));
  Widget _stage(List<Map<String,dynamic>> members){final active=members.where((m)=>m['left_at']==null).toList();return GridView.builder(padding:const EdgeInsets.fromLTRB(14,18,14,8),physics:const BouncingScrollPhysics(),itemCount:15,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3,mainAxisSpacing:12,crossAxisSpacing:10,childAspectRatio:.82),itemBuilder:(_,i){Map<String,dynamic>? m;for(final row in active){if(row['seat_no']==i+1){m=row;break;}}return _seat(i+1,m);});}
  Widget _seat(int no,Map<String,dynamic>? member){final profile=member?['profiles'] as Map<String,dynamic>?;final name=(profile?['display_name']??profile?['username']??'').toString();final avatar=(profile?['avatar_url']??'').toString();final isMuted=member?['muted']==true;return Column(mainAxisAlignment:MainAxisAlignment.center,children:[Stack(alignment:Alignment.bottomRight,children:[Container(width:64,height:64,decoration:BoxDecoration(shape:BoxShape.circle,color:const Color(0xFF28124F),border:Border.all(color:member==null?const Color(0xFF6B4B86):AsmarTheme.gold,width:2)),child:avatar.isNotEmpty?ClipOval(child:Image.network(avatar,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.person,color:Colors.white70,size:30))):Icon(member==null?Icons.mic_none:Icons.person,color:Colors.white70,size:30)),Container(padding:const EdgeInsets.symmetric(horizontal:5,vertical:2),decoration:BoxDecoration(color:const Color(0xFF0E071B),borderRadius:BorderRadius.circular(8)),child:Text('NO.$no',style:const TextStyle(color:AsmarTheme.gold,fontSize:8,fontWeight:FontWeight.bold)))]),const SizedBox(height:5),Text(member==null?'فارغ':(isMuted?'🔇 $name':name),maxLines:1,overflow:TextOverflow.ellipsis,style:TextStyle(color:member==null?Colors.white54:Colors.white,fontSize:10,fontWeight:member==null?FontWeight.normal:FontWeight.bold))]);}
  Widget _chat()=>Container(margin:const EdgeInsets.symmetric(horizontal:12,vertical:5),padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:Colors.black26,borderRadius:BorderRadius.circular(14)),child:const Row(children:[Icon(Icons.cloud_done,color:AsmarTheme.gold,size:18),SizedBox(width:7),Expanded(child:Text('متصل مباشرة بـ Supabase Realtime',style:TextStyle(color:Colors.white70,fontSize:12)))]));
  Widget _bottomBar(BuildContext context)=>Container(padding:const EdgeInsets.fromLTRB(12,8,12,10),decoration:const BoxDecoration(color:Color(0xDD120822)),child:Row(children:[_action(context,Icons.card_giftcard,'هدايا',()=>_sheet(context,RoomGiftsSheet(roomId:widget.roomId,members:_memberIds()))),_action(context,Icons.rocket_launch,'ألعاب',()=>_sheet(context,const RoomGamesSheet())),_action(context,muted?Icons.mic_off:Icons.mic,'مايك',_toggleMute),_action(context,Icons.build_circle_outlined,'أدوات',()=>_sheet(context,const RoomToolsSheet()))]));
  List<String> _memberIds()=>currentMembers.where((m)=>m['left_at']==null&&m['user_id']!=client.auth.currentUser?.id).map((m)=>m['user_id'].toString()).toList();
  Future<void> _toggleMute() async {try{final next=!muted;await client.rpc('set_room_mute',params:{'p_room_id':widget.roomId,'p_muted':next});if(mounted)setState(()=>muted=next);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر تغيير المايك: $e')));}}
  Widget _action(BuildContext context,IconData icon,String label,VoidCallback onTap)=>Expanded(child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(14),child:Padding(padding:const EdgeInsets.symmetric(vertical:4),child:Column(children:[Icon(icon,color:AsmarTheme.gold,size:25),const SizedBox(height:3),Text(label,style:const TextStyle(color:Colors.white70,fontSize:10))]))));
}
