import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

const _gold=Color(0xFFFFD36A),_bg=Color(0xFF090604),_card=Color(0xFF1B0E08);

class AdminFinancePage extends StatefulWidget{const AdminFinancePage({super.key});@override State<AdminFinancePage> createState()=>_AdminFinancePageState();}
class _AdminFinancePageState extends State<AdminFinancePage>{
 int tab=0;bool loading=true;List<Map<String,dynamic>> methods=[],agents=[],requests=[];
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{try{final c=Supabase.instance.client;methods=List<Map<String,dynamic>>.from(await c.from('withdrawal_methods').select('*').order('sort_order'));agents=List<Map<String,dynamic>>.from(await c.from('recharge_agents').select('*').order('sort_order'));requests=List<Map<String,dynamic>>.from(await c.from('withdrawal_requests').select('*,withdrawal_methods(name)').order('created_at',ascending:false).limit(100));}catch(e){_msg('تعذر التحميل: '+e.toString());}if(mounted)setState(()=>loading=false);}
 void _msg(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
 Future<void> _method([Map<String,dynamic>? old])async{final n=TextEditingController(text:old?['name']?.toString()??''),cur=TextEditingController(text:old?['currency']?.toString()??'USD'),min=TextEditingController(text:old?['min_amount']?.toString()??'0'),max=TextEditingController(text:old?['max_amount']?.toString()??'0'),fee=TextEditingController(text:old?['fee']?.toString()??'0');await showDialog(context:context,builder:(d)=>AlertDialog(backgroundColor:_card,title:Text(old==null?'إضافة طريقة سحب':'تعديل طريقة السحب',style:const TextStyle(color:_gold)),content:Column(mainAxisSize:MainAxisSize.min,children:[_f(n,'اسم البنك/الطريقة'),_f(cur,'العملة'),_f(min,'الحد الأدنى'),_f(max,'الحد الأقصى'),_f(fee,'الرسوم')]),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('إلغاء')),FilledButton(onPressed:()async{final data={'name':n.text.trim(),'currency':cur.text.trim(),'min_amount':int.tryParse(min.text)??0,'max_amount':int.tryParse(max.text)??0,'fee':double.tryParse(fee.text)??0};try{final c=Supabase.instance.client;if(old==null)await c.from('withdrawal_methods').insert(data);else await c.from('withdrawal_methods').update(data).eq('id',old['id']);if(d.mounted)Navigator.pop(d);await _load();}catch(e){_msg('فشل الحفظ: '+e.toString());}},child:const Text('حفظ'))]));}
 Widget _f(TextEditingController c,String l)=>Padding(padding:const EdgeInsets.only(bottom:8),child:TextField(controller:c,style:const TextStyle(color:Colors.white),decoration:InputDecoration(labelText:l)));
 Future<void> _agent([Map<String,dynamic>? old])async{final profiles=List<Map<String,dynamic>>.from(await Supabase.instance.client.from('profiles').select('id,display_name,username').eq('role','AGENT').order('display_name'));if(profiles.isEmpty){_msg('لا يوجد حسابات AGENT');return;}final n=TextEditingController(text:old?['display_name']?.toString()??''),p=TextEditingController(text:old?['whatsapp_number']?.toString()??'');String pid=old?['profile_id']?.toString()??profiles.first['id'].toString();await showDialog(context:context,builder:(d)=>AlertDialog(backgroundColor:_card,title:Text(old==null?'إضافة وكيل شحن':'تعديل وكيل',style:const TextStyle(color:_gold)),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(value:pid,items:profiles.map((x)=>DropdownMenuItem(value:x['id'].toString(),child:Text((x['display_name']??x['username']??'وكيل').toString()))).toList(),onChanged:(v){if(v!=null)pid=v;}),_f(n,'اسم الوكيل'),_f(p,'رقم WhatsApp')]),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('إلغاء')),FilledButton(onPressed:()async{try{final data={'profile_id':pid,'display_name':n.text.trim(),'whatsapp_number':p.text.trim()};final c=Supabase.instance.client;if(old==null)await c.from('recharge_agents').insert(data);else await c.from('recharge_agents').update(data).eq('id',old['id']);if(d.mounted)Navigator.pop(d);await _load();}catch(e){_msg('فشل الحفظ: '+e.toString());}},child:const Text('حفظ'))]));}
 Future<void> _status(String id,String s)async{try{await Supabase.instance.client.from('withdrawal_requests').update({'status':s}).eq('id',id);await _load();}catch(e){_msg('فشل التحديث: '+e.toString());}}
 @override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:_bg,appBar:AppBar(title:const Text('إدارة السحب ووكلاء الشحن'),actions:[IconButton(onPressed:_load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator(color:_gold)):Column(children:[Padding(padding:const EdgeInsets.all(8),child:Row(children:[_tab(0,'طرق السحب'),_tab(1,'وكلاء الشحن'),_tab(2,'طلبات السحب')])),Expanded(child:tab==0?_methods():tab==1?_agents():_requests())])));
 Widget _tab(int i,String t)=>Expanded(child:Padding(padding:const EdgeInsets.all(3),child:OutlinedButton(onPressed:()=>setState(()=>tab=i),style:OutlinedButton.styleFrom(foregroundColor:tab==i?_gold:Colors.white70),child:Text(t))));
 Widget _methods()=>ListView(padding:const EdgeInsets.all(16),children:[FilledButton.icon(onPressed:()=>_method(),icon:const Icon(Icons.add),label:const Text('إضافة طريقة سحب')),const SizedBox(height:10),...methods.map((m)=>Card(color:_card,child:ListTile(title:Text(m['name'].toString(),style:const TextStyle(color:Colors.white)),subtitle:Text(m['currency'].toString()),trailing:IconButton(onPressed:()=>_method(m),icon:const Icon(Icons.edit,color:_gold)))))]);
 Widget _agents()=>ListView(padding:const EdgeInsets.all(16),children:[FilledButton.icon(onPressed:()=>_agent(),icon:const Icon(Icons.person_add),label:const Text('إضافة وكيل شحن')),const SizedBox(height:10),...agents.map((a)=>Card(color:_card,child:ListTile(title:Text(a['display_name'].toString(),style:const TextStyle(color:Colors.white)),subtitle:Text(a['whatsapp_number'].toString(),style:const TextStyle(color:_gold)),trailing:IconButton(onPressed:()=>_agent(a),icon:const Icon(Icons.edit,color:_gold)))))]);
 Widget _requests()=>ListView.separated(padding:const EdgeInsets.all(16),itemCount:requests.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(c,i){final r=requests[i];final m=(r['withdrawal_methods']??{}) as Map;return Card(color:_card,child:ListTile(title:Text(r['amount'].toString()+' • '+(m['name']??'طريقة').toString(),style:const TextStyle(color:Colors.white)),subtitle:Text(r['status'].toString(),style:const TextStyle(color:Colors.white60)),trailing:PopupMenuButton<String>(onSelected:(s)=>_status(r['id'].toString(),s),itemBuilder:(_)=>const[PopupMenuItem(value:'approved',child:Text('موافقة')),PopupMenuItem(value:'paid',child:Text('تم الدفع')),PopupMenuItem(value:'rejected',child:Text('رفض'))]));}};
}
