import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
const _gold=Color(0xFFFFD36A),_bg=Color(0xFF100805);
class AsmarKeyboard extends StatefulWidget{final TextEditingController controller;final Future<void> Function() onSend;final String roomId;final void Function(Map<String,dynamic> gift)? onGiftSent;const AsmarKeyboard({super.key,required this.controller,required this.onSend,required this.roomId,this.onGiftSent});@override State<AsmarKeyboard> createState()=>_AsmarKeyboardState();}
class _AsmarKeyboardState extends State<AsmarKeyboard>{int tab=0;bool sending=false;List<Map<String,dynamic>> gifts=[];final recipient=TextEditingController();
@override void initState(){super.initState();_load();}@override void dispose(){recipient.dispose();super.dispose();}
Future<void> _load()async{try{final r=await Supabase.instance.client.from('gifts').select('id,name,emoji,price_coins,animation_url,is_active').eq('is_active',true).order('price_coins');if(mounted)setState(()=>gifts=List<Map<String,dynamic>>.from(r));}catch(_){} }
Future<void> _gift(Map<String,dynamic> g)async{final to=recipient.text.trim();if(to.isEmpty||sending)return;setState(()=>sending=true);try{await Supabase.instance.client.rpc('send_gift',params:{'p_room_id':widget.roomId,'p_recipient_id':to,'p_gift_id':g['id']});widget.onGiftSent?.call(g);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر إرسال الهدية: $e')));}finally{if(mounted)setState(()=>sending=false);}}
Widget _tab(int i,String icon,String label)=>Expanded(child:InkWell(onTap:()=>setState(()=>tab=i),child:Padding(padding:const EdgeInsets.all(7),child:Column(children:[Text(icon,style:const TextStyle(fontSize:21)),Text(label,style:TextStyle(color:tab==i?_gold:Colors.white60,fontSize:10,fontWeight:FontWeight.w800))]))));
Widget _content(){if(tab==1)return Column(children:[TextField(controller:recipient,style:const TextStyle(color:Colors.white),decoration:const InputDecoration(prefixIcon:Icon(Icons.person_search,color:_gold),hintText:'ID المستلم')),const SizedBox(height:4),Expanded(child:GridView.builder(itemCount:gifts.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:4,childAspectRatio:.82),itemBuilder:(_,i){final g=gifts[i];return InkWell(onTap:sending?null:()=>_gift(g),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(g['emoji']?.toString()??'🎁',style:const TextStyle(fontSize:28)),Text(g['name']?.toString()??'',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white,fontSize:10)),Text('${g['price_coins']??0} 🪙',style:const TextStyle(color:_gold,fontSize:9))]));}))]);
final chars=tab==0?['😀','😃','😂','🤣','😊','😍','🥰','😘','😎','🤩','🥳','😢','😭','😡','🤔','😴','🙈','❤️','💕','💯','🔥','✨','🎉','👏','👍','🙏','💎','👑','🌹','🚘','🫶','🤝']:['🔥','💖','👑','💎','🎉','🥳','😂','😍','😎','❤️','✨','🌹','🚘','🫶','🤝','🏆'];return GridView.count(crossAxisCount:8,children:chars.map((x)=>InkWell(onTap:()=>setState(()=>widget.controller.text+=' $x'),child:Center(child:Text(x,style:const TextStyle(fontSize:27))))).toList());}
@override Widget build(BuildContext context)=>Material(color:_bg,child:SafeArea(top:false,child:Container(height:280,padding:const EdgeInsets.fromLTRB(10,6,10,8),decoration:const BoxDecoration(color:_bg,borderRadius:BorderRadius.vertical(top:Radius.circular(24))),child:Column(children:[Row(children:[Expanded(child:TextField(controller:widget.controller,style:const TextStyle(color:Colors.white),decoration:const InputDecoration(hintText:'اكتب رسالة…',prefixIcon:Icon(Icons.alternate_email,color:_gold)))),IconButton(onPressed:widget.onSend,icon:const Icon(Icons.send,color:_gold))]),const Divider(color:Colors.white12),Row(children:[_tab(0,'😊','Emoji'),_tab(1,'🎁','هدايا'),_tab(2,'✨','Stickers')]),Expanded(child:_content())])));}
