import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'country_flag.dart';
import 'rank_frame.dart';

class PrivateChatPage extends StatefulWidget{final String friendId;const PrivateChatPage({super.key,required this.friendId});@override State<PrivateChatPage> createState()=>_PrivateChatPageState();}
class _PrivateChatPageState extends State<PrivateChatPage>{
 final input=TextEditingController(); final c=Supabase.instance.client;
 Future<void> send()async{final m=input.text.trim();if(m.isEmpty)return;try{await c.rpc('send_private_message',params:{'p_receiver':widget.friendId,'p_message':m});input.clear();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر إرسال الرسالة: $e')));}}
 @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFF090604),appBar:AppBar(backgroundColor:const Color(0xFF100805),foregroundColor:Colors.white,title:FutureBuilder<Map<String,dynamic>>(future:c.from('profiles').select('username,role,country_code,vip_level,avatar_url').eq('id',widget.friendId).maybeSingle().then((v)=>Map<String,dynamic>.from(v??{})),builder:(ctx,s){final p=s.data??{};final name=p['username']?.toString()??'مستخدم';return Row(children:[RankFrame(role:p['role']?.toString()??'USER',vipLevel:p['vip_level']?.toString(),size:34,showLabel:false,child:CircleAvatar(backgroundColor:const Color(0xFF120A06),backgroundImage:(p['avatar_url']?.toString()??'').isNotEmpty?NetworkImage(p['avatar_url'].toString()):null,child:(p['avatar_url']?.toString()??'').isEmpty?const Icon(Icons.person,color:Color(0xFFFFD36A),size:18):null)),const SizedBox(width:6),CountryFlag(code:p['country_code']?.toString(),size:18),const SizedBox(width:5),Flexible(child:Text(name,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Color(0xFFFFD36A),fontWeight:FontWeight.w900)))]);})),body:Column(children:[
 Expanded(child:StreamBuilder<List<Map<String,dynamic>>>(stream:c.from('private_messages').stream(primaryKey:['id']),builder:(ctx,s){final uid=c.auth.currentUser?.id;final rows=(s.data??[]).where((x)=>(x['sender_id']==uid&&x['receiver_id']==widget.friendId)||(x['sender_id']==widget.friendId&&x['receiver_id']==uid)).toList()..sort((a,b)=>DateTime.parse(a['created_at']).compareTo(DateTime.parse(b['created_at'])));return ListView.builder(padding:const EdgeInsets.all(12),itemCount:rows.length,itemBuilder:(ctx,i){final x=rows[i];final mine=x['sender_id']==uid;return Align(alignment:mine?Alignment.centerRight:Alignment.centerLeft,child:Container(margin:const EdgeInsets.symmetric(vertical:4),padding:const EdgeInsets.all(12),constraints:const BoxConstraints(maxWidth:320),decoration:BoxDecoration(color:mine?const Color(0xFF4A2C08):const Color(0xFF1B0E08),borderRadius:BorderRadius.circular(16)),child:Text(x['message'],style:const TextStyle(color:Colors.white)));});})),
 Padding(padding:const EdgeInsets.fromLTRB(10,6,10,12),child:Row(children:[Expanded(child:TextField(controller:input,style:const TextStyle(color:Colors.white),decoration:const InputDecoration(hintText:'اكتب رسالة...',hintStyle:TextStyle(color:Colors.white38)))),IconButton(onPressed:send,icon:const Icon(Icons.send,color:Color(0xFFFFD36A))) ]))
 ]));
}