import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
const _gold=Color(0xFFFFD36A),_bg=Color(0xFF090604),_card=Color(0xFF211108);final _db=Supabase.instance.client;
class SuperAdminPanel extends StatefulWidget{const SuperAdminPanel({super.key});@override State<SuperAdminPanel> createState()=>_SuperAdminPanelState();}
class _SuperAdminPanelState extends State<SuperAdminPanel>{int tab=0;bool loading=true;List<Map<String,dynamic>> users=[],rooms=[],coins=[],vips=[],items=[],gifts=[];
@override void initState(){super.initState();load();}
Future<void> load()async{setState(()=>loading=true);try{final r=await Future.wait([_db.from('profiles').select('id,public_id,display_name,username,coins,diamonds,vip_level,is_blocked').order('created_at',ascending:false).limit(100),_db.from('rooms').select('id,name,owner_id,is_active,hot_score,created_at').order('created_at',ascending:false).limit(100),_db.from('coin_packages').select().order('created_at',ascending:false),_db.from('vip_packages').select().order('tier').order('billing_period'),_db.from('store_items').select().order('created_at',ascending:false),_db.from('gifts').select().order('created_at',ascending:false)]);users=List<Map<String,dynamic>>.from(r[0]);rooms=List<Map<String,dynamic>>.from(r[1]);coins=List<Map<String,dynamic>>.from(r[2]);vips=List<Map<String,dynamic>>.from(r[3]);items=List<Map<String,dynamic>>.from(r[4]);gifts=List<Map<String,dynamic>>.from(r[5]);}catch(e){_msg('خطأ التحميل: $e');}finally{if(mounted)setState(()=>loading=false);}}
void _msg(String s){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));}
Future<void> action(String a,String id,{int amount=0,int vip=0})async{try{if(a=='coins')await _db.rpc('admin_grant_coins',params:{'p_user_id':id,'p_amount':amount,'p_reason':'super_admin_panel'});if(a=='vip')await _db.rpc('admin_grant_vip',params:{'p_user_id':id,'p_level':vip,'p_days':30});if(a=='block'||a=='unblock')await _db.rpc('admin_set_user_blocked',params:{'p_user_id':id,'p_blocked':a=='block'});if(a=='close')await _db.rpc('admin_close_room',params:{'p_room_id':id});await load();}catch(e){_msg('فشلت العملية: $e');}}
Future<void> form(String title,Map<String,dynamic>? old,Future<void> Function(Map<String,String>) save,List<String> fields)async{final c={for(final f in fields)f:TextEditingController(text:old?[f]?.toString()??'')};final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(backgroundColor:_card,title:Text(title),content:SingleChildScrollView(child:Column(children:fields.map((f)=>Padding(padding:const EdgeInsets.only(bottom:8),child:TextField(controller:c[f],decoration:InputDecoration(labelText:f)))).toList())),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('حفظ'))]));if(ok==true){await save({for(final e in c.entries)e.key:e.value.text.trim()});await load();}}
Future<void> coinSave(Map<String,String>d,String?id)async{final x={'name':d['name'],'coins':int.tryParse(d['coins']??'0')??0,'price_usd':double.tryParse(d['price_usd']??'0')??0,'is_active':true};if(id==null)await _db.from('coin_packages').insert(x);else await _db.from('coin_packages').update(x).eq('id',id);}
Future<void> vipSave(Map<String,String>d,String?id)async{final x={'name':d['name'],'tier':d['tier'],'billing_period':d['billing_period'],'price_usd':double.tryParse(d['price_usd']??'0')??0,'coin_price':int.tryParse(d['coin_price']??'0'),'is_active':true};if(id==null)await _db.from('vip_packages').insert(x);else await _db.from('vip_packages').update(x).eq('id',id);}
Future<void> itemSave(Map<String,String>d,String?id)async{final x={'name':d['name'],'item_type':d['item_type'],'price_coins':int.tryParse(d['price_coins']??'0')??0,'asset_url':d['asset_url'],'animation_url':d['animation_url'],'is_active':true};if(id==null)await _db.from('store_items').insert(x);else await _db.from('store_items').update(x).eq('id',id);}
Future<void> giftSave(Map<String,String>d,String?id)async{final x={'name':d['name'],'price_coins':int.tryParse(d['price_coins']??'0')??0,'animation_url':d['animation_url'],'is_active':true};if(id==null)await _db.from('gifts').insert(x);else await _db.from('gifts').update(x).eq('id',id);}
Widget card(String title,String sub,VoidCallback edit,VoidCallback del)=>Card(color:_card,child:ListTile(title:Text(title),subtitle:Text(sub),trailing:Wrap(children:[IconButton(onPressed:edit,icon:const Icon(Icons.edit,color:_gold)),IconButton(onPressed:del,icon:const Icon(Icons.delete_outline,color:Colors.redAccent))])));
Widget section(String title,Widget body,VoidCallback add)=>ListView(children:[Row(children:[Expanded(child:Text(title,style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:_gold))),IconButton(onPressed:add,icon:const Icon(Icons.add_circle,color:_gold))]),body]);
Widget _body(){switch(tab){case 1:return _users();case 2:return _packages();case 3:return _gifts();case 4:return _store();case 5:return _rooms();default:return _dashboard();}}
Widget _dashboard()=>ListView(children:[const Text('لوحة Super Admin',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900,color:_gold)),const SizedBox(height:18),Wrap(spacing:10,runSpacing:10,children:[_stat('المستخدمون',users.length,Icons.people),_stat('الغرف المباشرة',rooms.where((r)=>r['is_active']==true).length,Icons.mic),_stat('إجمالي الكوينز',users.fold<num>(0,(a,u)=>a+((u['coins'] as num?)??0)),Icons.monetization_on)]),const SizedBox(height:20),FutureBuilder(future:_db.from('wallet_transactions').select('amount,created_at').gte('created_at',DateTime.now().subtract(const Duration(days:30)).toIso8601String()),builder:(_,s){final x=List<Map<String,dynamic>>.from(s.data??const[]);return Card(color:_card,child:ListTile(title:const Text('إحصائيات الأرباح — آخر 30 يوم'),subtitle:Text('${x.length} عملية'),trailing:Text('${x.fold<num>(0,(a,r)=>a+((r['amount'] as num?)??0))}')));})]);
Widget _stat(String t,Object v,IconData i)=>SizedBox(width:220,height:120,child:Card(color:_card,child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:_gold),const Spacer(),Text('$v',style:const TextStyle(fontSize:26,fontWeight:FontWeight.w900)),Text(t,style:const TextStyle(color:Colors.white60))]))));
Widget _users()=>ListView(children:[const Text('إدارة المستخدمين',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:_gold)),...users.map((u)=>card('${u['display_name']??u['username']??'مستخدم'} • ID ${u['public_id']??''}','Coins: ${u['coins']??0} • Level: ${u['vip_level']??0}',(){showModalBottomSheet(context:context,builder:(_)=>Column(mainAxisSize:MainAxisSize.min,children:[ListTile(title:const Text('إعطاء 1000 كوين'),onTap:(){Navigator.pop(context);action('coins',u['id'].toString(),amount:1000);}),ListTile(title:const Text('إعطاء أرستقراطية مستوى 10'),onTap:(){Navigator.pop(context);action('vip',u['id'].toString(),vip:10);}),ListTile(title:Text(u['is_blocked']==true?'فك الحظر':'حظر'),onTap:(){Navigator.pop(context);action(u['is_blocked']==true?'unblock':'block',u['id'].toString());})]));},()=>action(u['is_blocked']==true?'unblock':'block',u['id'].toString()))]);
Widget _packages()=>ListView(children:[Row(children:[Expanded(child:const Text('باقات الكوينز',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:_gold))),IconButton(onPressed:()=>form('إضافة باقة',null,(d)=>coinSave(d,null),['name','coins','price_usd']),icon:const Icon(Icons.add_circle,color:_gold))]),...coins.map((r)=>card(r['name'].toString(),'${r['coins']} كوين = \$${r['price_usd']}',()=>form('تعديل',r,(d)=>coinSave(d,r['id'].toString()),['name','coins','price_usd']),()=>_db.from('coin_packages').delete().eq('id',r['id']).then((_){load();}))),const SizedBox(height:18),Row(children:[Expanded(child:const Text('باقات الأرستقراطية',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:_gold))),IconButton(onPressed:()=>form('إضافة باقة',null,(d)=>vipSave(d,null),['name','tier','billing_period','price_usd','coin_price']),icon:const Icon(Icons.add_circle,color:_gold))]),...vips.map((r)=>card(r['name'].toString(),'${r['billing_period']} • \$${r['price_usd']}',()=>form('تعديل',r,(d)=>vipSave(d,r['id'].toString()),['name','tier','billing_period','price_usd','coin_price']),()=>_db.from('vip_packages').delete().eq('id',r['id']).then((_){load();}))) ]);
Widget _gifts()=>section('الهدايا',Column(children:gifts.map((r)=>card(r['name'].toString(),'${r['price_coins']} كوين • ${r['animation_url']??''}',()=>form('تعديل هدية',r,(d)=>giftSave(d,r['id'].toString()),['name','price_coins','animation_url']),()=>_db.from('gifts').delete().eq('id',r['id']).then((_){load();}))).toList()),()=>form('إضافة هدية',null,(d)=>giftSave(d,null),['name','price_coins','animation_url']));
Widget _store()=>section('المتجر',Column(children:items.map((r)=>card(r['name'].toString(),'${r['item_type']} • ${r['price_coins']} كوين',()=>form('تعديل عنصر',r,(d)=>itemSave(d,r['id'].toString()),['name','item_type','price_coins','asset_url','animation_url']),()=>_db.from('store_items').delete().eq('id',r['id']).then((_){load();}))).toList()),()=>form('إضافة عنصر',null,(d)=>itemSave(d,null),['name','item_type','price_coins','asset_url','animation_url']));
Widget _rooms()=>ListView(children:[const Text('الغرف المباشرة',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:_gold)),...rooms.where((r)=>r['is_active']==true).map((r)=>card(r['name'].toString(),'Hot: ${r['hot_score']??0}',(){},()=>action('close',r['id'].toString()))) ]);
@override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:_bg,appBar:AppBar(title:const Text('SUPER ADMIN',style:TextStyle(color:_gold,fontWeight:FontWeight.w900)),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator(color:_gold)):Row(children:[NavigationRail(backgroundColor:_card,selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),labelType:NavigationRailLabelType.all,destinations:const[NavigationRailDestination(icon:Icon(Icons.dashboard_outlined),label:Text('الرئيسية')),NavigationRailDestination(icon:Icon(Icons.people_outline),label:Text('المستخدمون')),NavigationRailDestination(icon:Icon(Icons.monetization_on_outlined),label:Text('الباقات')),NavigationRailDestination(icon:Icon(Icons.card_giftcard),label:Text('الهدايا')),NavigationRailDestination(icon:Icon(Icons.storefront_outlined),label:Text('المتجر')),NavigationRailDestination(icon:Icon(Icons.meeting_room_outlined),label:Text('الغرف'))]),Expanded(child:Padding(padding:const EdgeInsets.all(16),child:_body()))]));}
