import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class VipLevelData{final String id,animal,icon,description;final int price;final List<String> perks;const VipLevelData({required this.id,required this.animal,required this.icon,required this.description,required this.price,required this.perks});}
const vipLevels=<VipLevelData>[
VipLevelData(id:'VIP1',animal:'الغزال',icon:'🦌',description:'بداية مسار VIP',price:10000,perks:['إطار VIP','شارة VIP','مزايا استلام العملات']),VipLevelData(id:'VIP2',animal:'الذئب',icon:'🐺',description:'مستوى VIP متقدم',price:25000,perks:['إطار VIP','شارة VIP','مزايا استلام العملات']),VipLevelData(id:'VIP3',animal:'التمساح',icon:'🐊',description:'نمط VIP مميز',price:50000,perks:['نمط حصري','اسم مستخدم مميز','إطار VIP']),VipLevelData(id:'VIP4',animal:'الفيل',icon:'🐘',description:'مزايا الغرف والبطاقة',price:90000,perks:['نمط غرفة','نمط بطاقة التعريف','مزايا استلام العملات']),VipLevelData(id:'VIP5',animal:'النسر',icon:'🦅',description:'مستوى النسر',price:150000,perks:['مزايا الغرفة','اسم ميكروفون مجاني','رسائل غير محدودة']),VipLevelData(id:'VIP6',animal:'الدب',icon:'🐻',description:'مستوى الدب',price:250000,perks:['مزايا الغرفة','اسم ميكروفون مجاني','رسائل غير محدودة']),VipLevelData(id:'VIP7',animal:'الفهد',icon:'🐆',description:'مستوى الفهد',price:400000,perks:['نمط بطاقة التعريف','اسم مجاني','مزايا استلام العملات']),VipLevelData(id:'VIP8',animal:'النمر',icon:'🐯',description:'مستوى النمر',price:650000,perks:['اسم مميز','شارة VIP','مزايا استلام العملات']),VipLevelData(id:'VIP9',animal:'التنين',icon:'🐉',description:'مستوى أسطوري',price:1000000,perks:['مزايا الغرفة','اسم ميكروفون مجاني','رسائل غير محدودة']),VipLevelData(id:'VIP10',animal:'الأسد',icon:'🦁',description:'أعلى مستوى VIP',price:1500000,perks:['ترحيب أسطوري','دخول الغرفة بتأثير','كل المميزات'])];
class VipPage extends StatefulWidget{const VipPage({super.key});@override State<VipPage> createState()=>_VipPageState();}
class _VipPageState extends State<VipPage>{int balance=0;String? currentVip;bool loading=true;@override void initState(){super.initState();_load();}Future<void> _load() async{final c=Supabase.instance.client;final u=c.auth.currentUser;if(u==null)return;final w=await c.from('wallets').select('balance').eq('user_id',u.id).maybeSingle();final p=await c.from('profiles').select('vip_level').eq('id',u.id).maybeSingle();if(!mounted)return;setState((){balance=(w?['balance'] as num?)?.toInt()??0;currentVip=p?['vip_level']?.toString();loading=false;});}Future<void> _buy(VipLevelData v) async{try{await Supabase.instance.client.rpc('purchase_vip',params:{'p_vip_level':v.id});await _load();if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(v.id+' '+v.animal+' فعال الآن 🔥')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('VIP شراء فشل: $e')));}}
@override Widget build(BuildContext context){return Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:const Color(0xFF090604),appBar:AppBar(title:const Text('VIP 1 — VIP 10',style:TextStyle(fontWeight:FontWeight.w900)),actions:[Padding(padding:const EdgeInsets.all(14),child:Center(child:Text(loading?'...':balance.toString()+' 🪙',style:const TextStyle(color:Color(0xFFFFD36A),fontWeight:FontWeight.w900))))]),body:ListView.builder(padding:const EdgeInsets.all(14),itemCount:vipLevels.length,itemBuilder:(_,i){final v=vipLevels[i];final active=currentVip==v.id;return Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(16),decoration:BoxDecoration(borderRadius:BorderRadius.circular(22),gradient:const LinearGradient(colors:[Color(0xFF2A160A),Color(0xFF0D0704)]),border:Border.all(color:active?const Color(0xFFFFD36A):const Color(0xFF6A421A),width:active?2:1)),child:Row(children:[Container(width:70,height:70,decoration:const BoxDecoration(shape:BoxShape.circle,gradient:LinearGradient(colors:[Color(0xFFFFE08A),Color(0xFF8C4E0D)])),child:Center(child:Text(v.icon,style:const TextStyle(fontSize:38))),),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(v.id+' • '+v.animal,style:const TextStyle(color:Color(0xFFFFD36A),fontSize:18,fontWeight:FontWeight.w900)),Text(v.description,style:const TextStyle(color:Colors.white70,fontSize:12)),const SizedBox(height:6),Text(v.perks.join(' • '),style:const TextStyle(color:Colors.white54,fontSize:11)),const SizedBox(height:8),Row(children:[Text(v.price.toString()+' 🪙',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.bold)),const Spacer(),FilledButton(onPressed:active?null:()=>_buy(v),style:const ButtonStyle(backgroundColor:WidgetStatePropertyAll(Color(0xFFB77921))),child:Text(active?'مفعّل':'شراء'))])]))]));}));}}
