import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../room/widgets/create_room_sheet.dart';
import '../room/presentation/room_page.dart';
class BeelaShell extends StatefulWidget {const BeelaShell({super.key});@override State<BeelaShell> createState()=>_BeelaShellState();}
class _BeelaShellState extends State<BeelaShell> {
String f='الكل';Future<void> _create() async {
final c=await showModalBottomSheet<int>(context: context,backgroundColor: Colors.transparent,isScrollControlled: true,builder: (_)=>const CreateRoomSheet());
if(c==null)return;try{final u=Supabase.instance.client.auth.currentUser;final r=await Supabase.instance.client.from('rooms').insert({'name':'غرفة $c','seat_count':c,'owner_id':u?.id}).select().single();await Supabase.instance.client.from('seats').insert(List.generate(c,(i)=>{'room_id':r['id'],'seat_no':i}));if(!mounted)return;Navigator.push(context,MaterialPageRoute(builder: (_)=>RoomPage(roomId: r['id'],seatCount: c)));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('$e')));}}
@override Widget build(BuildContext context){return Scaffold(backgroundColor:const Color(0xFF0F0F1A),body:Column(children:[Container(height:200,decoration:const BoxDecoration(gradient: LinearGradient(colors: [Color(0xFFFFD700),Color(0xFFFF9800)]),borderRadius: BorderRadius.only(bottomLeft: Radius.circular(24),bottomRight: Radius.circular(24))),child:const Center(child: Text('أسمر شات 🔥',style: TextStyle(fontSize:32,fontWeight: FontWeight.bold)))),SizedBox(height:50,child: ListView(scrollDirection: Axis.horizontal,children: ['الكل','Hot 🔥','سوريا'].map((x)=>Padding(padding:const EdgeInsets.all(6),child: ChoiceChip(label: Text(x),selected: f==x,onSelected: (_)=>setState(()=>f=x)))).toList())),const Expanded(child: Center(child: Text('لا يوجد غرف - اضغط +',style: TextStyle(color: Colors.white54))))]),floatingActionButton: FloatingActionButton(onPressed: _create,backgroundColor: Colors.amber,child:const Icon(Icons.add,color: Colors.black)),);}}
