import 'package:flutter/material.dart';
import '../../asmar/asmar_theme.dart';
import '../room/room_screen.dart';

class BeelaShell extends StatefulWidget { const BeelaShell({super.key}); @override State<BeelaShell> createState()=>_BeelaShellState(); }
class _BeelaShellState extends State<BeelaShell> {
  int tab=0; String filter='Jordan 🇯🇴';
  final filters=const ['Jordan 🇯🇴','Turkey 🇹🇷','Syria 🇸🇾','Hot 🔥'];
  final rooms=const [('وكالة سليفة الغر','860998','🇸🇾','21','https://i.pravatar.cc/160?img=12',true),('هالة مرح الصبايا','479929','🇯🇴','18','https://i.pravatar.cc/160?img=32',false),('محرم VIP','62188','🇹🇷','36','https://i.pravatar.cc/160?img=45',false),('ASMAR HOT','55007','🔥','42','https://i.pravatar.cc/160?img=5',true)];
  @override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:CustomScrollView(slivers:[SliverToBoxAdapter(child:_header()),SliverToBoxAdapter(child:_banner()),SliverToBoxAdapter(child:_topRooms()),SliverToBoxAdapter(child:_tabs()),SliverToBoxAdapter(child:_filters()),SliverPadding(padding:const EdgeInsets.fromLTRB(12,8,12,28),sliver:SliverList.builder(itemCount:rooms.length,itemBuilder:(_,i)=>_room(rooms[i]))) ])));
  Widget _header()=>Container(height:205,decoration:const BoxDecoration(gradient:LinearGradient(colors:[Color(0xFF2A160B),Color(0xFF090604)],begin:Alignment.topCenter,end:Alignment.bottomCenter)),child:SafeArea(bottom:false,child:Padding(padding:const EdgeInsets.all(12),child:Column(children:[Row(children:[const Icon(Icons.mic,color:AsmarTheme.gold,size:28),const SizedBox(width:7),const Text('ASMAR',style:TextStyle(color:AsmarTheme.gold,fontSize:22,fontWeight:FontWeight.w900)),const Spacer(),IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none,color:Colors.white))]),const Spacer(),Container(height:44,decoration:BoxDecoration(color:Colors.black54,borderRadius:BorderRadius.circular(24),border:Border.all(color:Colors.white24)),child:const TextField(textDirection:TextDirection.rtl,style:TextStyle(color:Colors.white),decoration:InputDecoration(hintText:'ابحث عن الغرفة أو Room ID...',hintStyle:TextStyle(color:Colors.white60),prefixIcon:Icon(Icons.search,color:AsmarTheme.gold),border:InputBorder.none,contentPadding:EdgeInsets.symmetric(vertical:11))))]))));
  Widget _banner()=>Container(margin:const EdgeInsets.all(12),padding:const EdgeInsets.all(16),decoration:AsmarTheme.goldCard(radius:18),child:const Row(children:[Icon(Icons.card_giftcard,color:AsmarTheme.gold,size:34),SizedBox(width:12),Expanded(child:Text('تعالوا احصلوا على الهدية المخصصة الخاصة بك!',style:TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w900)))]));
  Widget _topRooms()=>SizedBox(height:126,child:ListView.separated(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:12),itemCount:3,separatorBuilder:(_,__)=>const SizedBox(width:10),itemBuilder:(_,i){final r=rooms[i];return Container(width:190,decoration:BoxDecoration(color:AsmarTheme.surface,borderRadius:BorderRadius.circular(18),border:Border.all(color:[Colors.redAccent,Colors.deepPurpleAccent,AsmarTheme.gold][i],width:2)),padding:const EdgeInsets.all(9),child:Row(children:[Stack(children:[CircleAvatar(radius:30,backgroundImage:NetworkImage(r.$5)),const Positioned(top:-4,right:-4,child:Text('👑',style:TextStyle(fontSize:20)))]),const SizedBox(width:8),Expanded(child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(r.$1,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),Text('${r.$3}  ${r.$4} شخص',style:const TextStyle(color:Colors.white60,fontSize:10)),Text('Room:${r.$2}',style:const TextStyle(color:AsmarTheme.gold,fontSize:10))]))]));}));
  Widget _tabs()=>Padding(padding:const EdgeInsets.fromLTRB(12,14,12,8),child:Row(children:['شائع','جديد','فيديو','متألق'].asMap().entries.map((e){final active=e.key==tab;return Expanded(child:GestureDetector(onTap:()=>setState(()=>tab=e.key),child:Container(padding:const EdgeInsets.symmetric(vertical:11),decoration:BoxDecoration(color:active?AsmarTheme.gold:AsmarTheme.surface,borderRadius:BorderRadius.circular(12)),child:Text(e.value,textAlign:TextAlign.center,style:TextStyle(color:active?Colors.black:Colors.white70,fontWeight:FontWeight.w800)))));}).toList()));
  Widget _filters()=>SizedBox(height:52,child:ListView.separated(padding:const EdgeInsets.symmetric(horizontal:12,vertical:7),scrollDirection:Axis.horizontal,itemCount:filters.length,separatorBuilder:(_,__)=>const SizedBox(width:8),itemBuilder:(_,i)=>ChoiceChip(label:Text(filters[i]),selected:filter==filters[i],onSelected:(_)=>setState(()=>filter=filters[i]),selectedColor:AsmarTheme.gold,labelStyle:TextStyle(color:filter==filters[i]?Colors.black:Colors.white70,fontWeight:FontWeight.bold),backgroundColor:AsmarTheme.surface,side:const BorderSide(color:Color(0xFF4B321A)))));
  Widget _room((String,String,String,String,String,bool) r)=>InkWell(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>RoomScreen(roomName:r.$1,roomId:r.$2))),borderRadius:BorderRadius.circular(16),child:Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:const Color(0xFFE9E0D6),borderRadius:BorderRadius.circular(16)),child:Row(children:[CircleAvatar(radius:32,backgroundImage:NetworkImage(r.$5)),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(r.$1,style:const TextStyle(color:Color(0xFF24180F),fontWeight:FontWeight.w900,fontSize:15)),const SizedBox(height:5),Row(children:[Text('Room:${r.$2}',style:const TextStyle(color:Color(0xFF675C54),fontSize:11)),const SizedBox(width:8),Text(r.$3,style:const TextStyle(fontSize:15)),const SizedBox(width:8),Icon(Icons.people_alt_outlined,color:Colors.green.shade700,size:14),const SizedBox(width:3),Text(r.$4,style:const TextStyle(color:Color(0xFF675C54),fontSize:11)),if(r.$6)const Padding(padding:EdgeInsets.only(left:7),child:Icon(Icons.lock_outline,size:15,color:Color(0xFF6A4030)))])),const Icon(Icons.chevron_left,color:Color(0xFF6A4030))]));
}
