async function loadGifts(){
 const root=document.getElementById('giftsTable'); if(!root)return;
 root.innerHTML='<div class="panel">جاري تحميل الهدايا...</div>';
 const {data,error}=await db.from('gifts').select('id,name,emoji,price,category,banner_enabled,banner_min_price,luck_min_win,is_active,asset_type,asset_url,preview_url,source_repo,source_license,animation_loop').order('price');
 if(error){root.innerHTML='<div class="panel">خطأ: '+escGift(error.message)+'</div>';return;}
 root.innerHTML=(data||[]).map(g=>'<div class="card gift-admin"><h3>'+escGift(g.emoji||'🎁')+' '+escGift(g.name)+'</h3><small>'+escGift(g.category||'normal')+' · '+escGift(g.asset_type||'emoji')+' · ID: '+escGift(g.id)+'</small><input id="gn_'+g.id+'" value="'+escGift(g.name)+'" placeholder="اسم الهدية"><input id="ge_'+g.id+'" value="'+escGift(g.emoji||'🎁')+'" placeholder="الإيموجي"><input id="gp_'+g.id+'" type="number" min="1" value="'+Number(g.price||1)+'" placeholder="السعر بالكوين"><input id="gc_'+g.id+'" value="'+escGift(g.category||'normal')+'" placeholder="الفئة"><select id="gt_'+g.id+'"><option value="emoji" '+(g.asset_type==='emoji'?'selected':'')+'>Emoji</option><option value="image" '+(g.asset_type==='image'?'selected':'')+'>صورة</option><option value="lottie" '+(g.asset_type==='lottie'?'selected':'')+'>Lottie متحرك</option><option value="3d" '+(g.asset_type==='3d'?'selected':'')+'>3D Model</option></select><input id="gu_'+g.id+'" value="'+escGift(g.asset_url||'')+'" placeholder="رابط ملف الهدية / animation / model"><input id="gprev_'+g.id+'" value="'+escGift(g.preview_url||'')+'" placeholder="رابط المعاينة"><input id="grep_'+g.id+'" value="'+escGift(g.source_repo||'')+'" placeholder="المصدر / GitHub"><input id="glic_'+g.id+'" value="'+escGift(g.source_license||'')+'" placeholder="الترخيص"><label><input id="gloop_'+g.id+'" type="checkbox" '+(g.animation_loop!==false?'checked':'')+'> تكرار الحركة</label><label><input id="ga_'+g.id+'" type="checkbox" '+(g.is_active?'checked':'')+'> فعالة</label><label><input id="gb_'+g.id+'" type="checkbox" '+(g.banner_enabled?'checked':'')+'> تظهر في شريط الإهداء</label><input id="gm_'+g.id+'" type="number" min="0" value="'+Number(g.banner_min_price||4000)+'" placeholder="حد الشريط بالكوين"><input id="gl_'+g.id+'" type="number" min="0" value="'+Number(g.luck_min_win||3000)+'" placeholder="حد الحظ بالكوين"><button onclick="saveGiftAdmin(\''+g.id+'\')">حفظ الهدية</button></div>').join('');
}
function openGiftCreate(){
 const root=document.getElementById('giftCreate'); if(!root)return;
 root.classList.remove('hidden');
 root.innerHTML='<div class="promo-grid"><input id="newGiftId" placeholder="ID فريد (مثال: golden_falcon_3d)"><input id="newGiftName" placeholder="اسم الهدية"><input id="newGiftEmoji" placeholder="الإيموجي" value="🎁"><input id="newGiftPrice" type="number" min="1" placeholder="السعر بالكوين"><input id="newGiftCategory" placeholder="الفئة" value="3d_luxury"><select id="newGiftType"><option value="emoji">Emoji</option><option value="image">صورة</option><option value="lottie" selected>Lottie متحرك</option><option value="3d">3D Model</option><option value="custom">مخصصة</option></select><input id="newGiftAssetUrl" placeholder="رابط ملف الهدية / animation / model"><input id="newGiftPreviewUrl" placeholder="رابط المعاينة / الصورة"><input id="newGiftSourceRepo" placeholder="المصدر / GitHub"><input id="newGiftLicense" placeholder="الترخيص"><input id="newGiftBannerMin" type="number" min="0" placeholder="حد شريط الإهداء" value="4000"><input id="newGiftLuckMin" type="number" min="0" placeholder="حد الحظ" value="3000"><label><input id="newGiftLoop" type="checkbox" checked> تكرار الحركة</label><label><input id="newGiftActive" type="checkbox" checked> فعالة</label><label><input id="newGiftBanner" type="checkbox"> تظهر في شريط الإهداء</label></div><div style="display:flex;gap:8px;margin-top:12px"><button class="primary" onclick="createGiftAdmin()">حفظ الهدية الجديدة</button><button class="ghost" onclick="document.getElementById(\'giftCreate\').classList.add(\'hidden\')">إلغاء</button></div>';
}
async function createGiftAdmin(){
 const id=document.getElementById('newGiftId').value.trim();
 const name=document.getElementById('newGiftName').value.trim();
 const emoji=document.getElementById('newGiftEmoji').value.trim()||'🎁';
 const price=Number(document.getElementById('newGiftPrice').value);
 const category=document.getElementById('newGiftCategory').value.trim()||'normal';
 const assetType=document.getElementById('newGiftType').value;
 const assetUrl=document.getElementById('newGiftAssetUrl').value.trim();
 if(!id||!name||!Number.isFinite(price)||price<1){alert('أدخل ID واسم الهدية وسعرًا صحيحًا');return;}
 const {error}=await db.rpc('ceo_create_gift',{p_id:id,p_name:name,p_emoji:emoji,p_price:price,p_category:category,p_is_active:document.getElementById('newGiftActive').checked,p_banner_enabled:document.getElementById('newGiftBanner').checked,p_banner_min_price:Number(document.getElementById('newGiftBannerMin').value||0),p_luck_min_win:Number(document.getElementById('newGiftLuckMin').value||0),p_asset_type:assetType,p_asset_url:assetUrl,p_preview_url:document.getElementById('newGiftPreviewUrl').value.trim(),p_source_repo:document.getElementById('newGiftSourceRepo').value.trim(),p_source_license:document.getElementById('newGiftLicense').value.trim(),p_animation_loop:document.getElementById('newGiftLoop').checked});
 if(error){alert('تعذر إضافة الهدية: '+error.message);return;}
 alert('تمت إضافة الهدية بنجاح'); document.getElementById('giftCreate').classList.add('hidden'); await loadGifts();
}
async function saveGiftAdmin(id){
 const price=Number(document.getElementById('gp_'+id).value), bannerMin=Number(document.getElementById('gm_'+id).value), luckMin=Number(document.getElementById('gl_'+id).value);
 if(!Number.isFinite(price)||price<1||bannerMin<0||luckMin<0){alert('قيم الهدية غير صحيحة');return;}
 const {error}=await db.rpc('ceo_update_gift',{p_id:id,p_name:document.getElementById('gn_'+id).value.trim(),p_emoji:document.getElementById('ge_'+id).value.trim()||'🎁',p_price:price,p_category:document.getElementById('gc_'+id).value.trim()||'normal',p_is_active:document.getElementById('ga_'+id).checked,p_banner_enabled:document.getElementById('gb_'+id).checked,p_banner_min_price:bannerMin,p_luck_min_win:luckMin,p_asset_type:document.getElementById('gt_'+id).value,p_asset_url:document.getElementById('gu_'+id).value.trim(),p_preview_url:document.getElementById('gprev_'+id).value.trim(),p_source_repo:document.getElementById('grep_'+id).value.trim(),p_source_license:document.getElementById('glic_'+id).value.trim(),p_animation_loop:document.getElementById('gloop_'+id).checked});
 if(error){alert('تعذر حفظ الهدية: '+error.message);return;}
 alert('تم حفظ الهدية بنجاح'); await loadGifts();
}
function escGift(v){return String(v??'').replace(/[&<>\\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#039;'}[m]))}
