async function loadGifts(){
 const root=document.getElementById('giftsTable'); if(!root)return;
 root.innerHTML='<div class="panel">جاري تحميل الهدايا...</div>';
 const {data,error}=await db.from('store_items').select('id,name,category,price_coins,image,description,rarity,is_active,is_lucky,banner_enabled,lucky_min_win_coins,gift_type').order('price_coins');
 if(error){root.innerHTML='<div class="panel">خطأ: '+escGift(error.message)+'</div>';return;}
 root.innerHTML=(data||[]).map(g=>'<div class="card gift-admin"><h3>🎁 '+escGift(g.name)+'</h3><small>'+escGift(g.category||'NORMAL')+' · '+escGift(g.gift_type||'NORMAL')+'</small><input id="gn_'+g.id+'" value="'+escGift(g.name)+'" placeholder="اسم الهدية"><input id="gp_'+g.id+'" type="number" min="0" value="'+Number(g.price_coins||0)+'" placeholder="السعر بالكوين"><input id="gc_'+g.id+'" value="'+escGift(g.category||'NORMAL')+'" placeholder="الفئة"><input id="gi_'+g.id+'" value="'+escGift(g.image||'')+'" placeholder="رابط صورة الهدية"><textarea id="gd_'+g.id+'" placeholder="الوصف">'+escGift(g.description||'')+'</textarea><input id="gr_'+g.id+'" value="'+escGift(g.rarity||'NORMAL')+'" placeholder="الندرة"><select id="gt_'+g.id+'"><option value="NORMAL" '+(g.gift_type==='NORMAL'?'selected':'')+'>هدية عادية</option><option value="LUCKY" '+(g.gift_type==='LUCKY'?'selected':'')+'>هدية حظ</option><option value="CP" '+(g.gift_type==='CP'?'selected':'')+'>CP</option><option value="LOVE" '+(g.gift_type==='LOVE'?'selected':'')+'>علاقة حب</option><option value="SIBLINGS" '+(g.gift_type==='SIBLINGS'?'selected':'')+'>علاقة أخوة</option></select><label><input id="ga_'+g.id+'" type="checkbox" '+(g.is_active?'checked':'')+'> فعالة</label><label><input id="gb_'+g.id+'" type="checkbox" '+(g.banner_enabled?'checked':'')+'> تظهر في شريط الإهداء</label><input id="gm_'+g.id+'" type="number" min="0" value="'+Number(g.lucky_min_win_coins||3000)+'" placeholder="حد ظهور الحظ بالكوين"><button onclick="saveGiftAdmin(\''+g.id+'\')">حفظ الهدية</button></div>').join('');
}
async function saveGiftAdmin(id){
 const type=document.getElementById('gt_'+id).value;
 const payload={p_id:id,p_name:document.getElementById('gn_'+id).value.trim(),p_category:document.getElementById('gc_'+id).value.trim()||'NORMAL',p_price_coins:Number(document.getElementById('gp_'+id).value),p_image:document.getElementById('gi_'+id).value.trim()||null,p_description:document.getElementById('gd_'+id).value.trim()||null,p_rarity:document.getElementById('gr_'+id).value.trim()||'NORMAL',p_is_active:document.getElementById('ga_'+id).checked,p_is_lucky:type==='LUCKY',p_banner_enabled:document.getElementById('gb_'+id).checked,p_lucky_min_win_coins:Number(document.getElementById('gm_'+id).value)||0,p_gift_type:type};
 const {error}=await db.rpc('admin_update_gift',payload); if(error){alert(error.message);return;} alert('تم حفظ الهدية بنجاح'); await loadGifts();
}
function escGift(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]))}
