-- Real VIP 1-10 system.
alter table public.profiles add column if not exists vip_level text;
create table if not exists public.vip_levels(id text primary key,animal text not null,price bigint not null check(price>=0),perks text[] not null default '{}',is_active boolean not null default true);
alter table public.vip_levels enable row level security;
drop policy if exists "vip_levels_select_active" on public.vip_levels;
create policy "vip_levels_select_active" on public.vip_levels for select to authenticated using(is_active=true);
insert into public.vip_levels(id,animal,price,perks) values ('VIP1','الغزال',10000,array['إطار VIP','شارة VIP','مزايا استلام العملات']),('VIP2','الذئب',25000,array['إطار VIP','شارة VIP','مزايا استلام العملات']),('VIP3','التمساح',50000,array['نمط حصري','اسم مستخدم مميز','إطار VIP']),('VIP4','الفيل',90000,array['نمط غرفة','نمط بطاقة التعريف','مزايا استلام العملات']),('VIP5','النسر',150000,array['مزايا الغرفة','اسم ميكروفون مجاني','رسائل غير محدودة']),('VIP6','الدب',250000,array['مزايا الغرفة','اسم ميكروفون مجاني','رسائل غير محدودة']),('VIP7','الفهد',400000,array['نمط بطاقة التعريف','اسم مجاني','مزايا استلام العملات']),('VIP8','النمر',650000,array['اسم مميز','شارة VIP','مزايا استلام العملات']),('VIP9','التنين',1000000,array['مزايا الغرفة','اسم ميكروفون مجاني','رسائل غير محدودة']),('VIP10','الأسد',1500000,array['ترحيب أسطوري','دخول الغرفة بتأثير','كل المميزات']) on conflict(id) do update set animal=excluded.animal,price=excluded.price,perks=excluded.perks;
create or replace function public.purchase_vip(p_vip_level text) returns public.profiles language plpgsql security definer set search_path=public as $$ declare v public.vip_levels;b bigint;p public.profiles;begin if auth.uid() is null then raise exception 'not authenticated';end if;select * into v from public.vip_levels where id=p_vip_level and is_active=true;if v.id is null then raise exception 'VIP not found';end if;select balance into b from public.wallets where user_id=auth.uid() for update;if b is null or b<v.price then raise exception 'insufficient coins';end if;update public.wallets set balance=balance-v.price,updated_at=now() where user_id=auth.uid();update public.profiles set vip_level=v.id,updated_at=now() where id=auth.uid() returning * into p;insert into public.coin_transactions(from_user_id,to_user_id,amount,reason) values(auth.uid(),null,v.price,'vip_purchase:'||v.id);return p;end;$$;
revoke all on function public.purchase_vip(text) from public;grant execute on function public.purchase_vip(text) to authenticated;
